"""
instantiator_gen — generates a new artifact instantiator from a CSV.

Given an artifact name + CSV file:
  1. Analyzes columns + infers types
  2. Generates instantiators/{name}_instantiator.py (from scaffold)
  3. Generates instantiators/templates/{name}/ (4 JSON template files)
  4. Generates Turtle patch for ioi-ext.ttl (new Facet + properties)
  5. Appends entry to data/ioi_registry.json (bundled registry)

After running, resolve_artifact(name) returns a registry hit.
"""

import json
import uuid
from pathlib import Path
from typing import Optional

from ioi_mcp.extension_gen import _to_facet_name, _to_property_name, IOI_EXT_NS, IOI_EXT_PREFIX
from ioi_mcp.type_inferencer import analyze_csv

KB_NAMESPACE = "https://ioi-framework.github.io/kb/"


# ── 4 Template JSON generators ────────────────────────────────────────────────

def _make_base_template(artifact_lower: str) -> dict:
    return {
        "@context": {
            "kb":         KB_NAMESPACE,
            "core":       "https://ontology.unifiedcyberontology.org/uco/core/",
            "observable": "https://ontology.unifiedcyberontology.org/uco/observable/",
            "uco-action": "https://ontology.unifiedcyberontology.org/uco/action/",
            "ioi-ext":    IOI_EXT_NS,
            "xsd":        "http://www.w3.org/2001/XMLSchema#",
        },
        "@graph": [],
    }


def _make_source_template(artifact_lower: str) -> list:
    return [{
        "@id":   f"kb:{artifact_lower}-source--{{SOURCE_UUID}}",
        "@type": "observable:File",
        "core:hasFacet": [{
            "@id":                    f"kb:{artifact_lower}-source-facet--{{SOURCE_UUID}}",
            "@type":                  "observable:FileFacet",
            "observable:fileName":    "{SOURCE_FILENAME}",
            "observable:filePath":    "{SOURCE_FILEPATH}",
            "observable:extension":   ".csv",
            "observable:sizeInBytes": {"@type": "xsd:integer", "@value": "{SOURCE_SIZE}"},
        }],
    }]


def _make_entry_template(artifact_lower: str, facet_name: str, columns: list) -> list:
    art_facet: dict = {
        "@id":   f"kb:{artifact_lower}-facet--{{ENTRY_UUID}}",
        "@type": [f"ioi-ext:{facet_name}", "core:Facet"],
    }
    for col in columns:
        prop = f"ioi-ext:{_to_property_name(artifact_lower, col['clean_name'])}"
        xsd  = col["inferred_type"]
        if xsd in ("xsd:integer", "xsd:dateTime", "xsd:boolean"):
            art_facet[prop] = {"@type": xsd, "@value": "{" + col["column_name"].upper() + "}"}
        else:
            art_facet[prop] = "{" + col["column_name"].upper() + "}"

    file_facet = {
        "@id":                  f"kb:{artifact_lower}-file-facet--{{ENTRY_UUID}}",
        "@type":                "observable:FileFacet",
        "observable:fileName":  "{FILE_NAME}",
        "observable:extension": "{FILE_EXTENSION}",
        "observable:filePath":  "{FILE_PATH}",
    }
    return [{
        "@id":           f"kb:{artifact_lower}--{{ENTRY_UUID}}",
        "@type":         "observable:File",
        "core:hasFacet": [file_facet, art_facet],
    }]


def _make_action_template(artifact_lower: str) -> list:
    return [{
        "@id":   f"kb:{artifact_lower}-action--{{ACTION_UUID}}",
        "@type": "uco-action:InvestigativeAction",
        "core:source": {"@id": f"kb:{artifact_lower}-source--{{SOURCE_UUID}}"},
        "core:target": {"@id": f"kb:{artifact_lower}--{{ENTRY_UUID}}"},
    }]


# ── Python instantiator script generator ─────────────────────────────────────

def _make_instantiator_script(artifact_name: str, facet_name: str, columns: list) -> str:
    art_lower = artifact_name.lower()

    def fmt_dict(d: dict) -> str:
        if not d:
            return "{}"
        inner = ",\n".join(f'    "{k}": "{v}"' for k, v in d.items())
        return "{\n" + inner + "\n}"

    int_fields  = {c["column_name"]: f"ioi-ext:{_to_property_name(artifact_name, c['clean_name'])}"
                   for c in columns if c["inferred_type"] == "xsd:integer"}
    dt_fields   = {c["column_name"]: f"ioi-ext:{_to_property_name(artifact_name, c['clean_name'])}"
                   for c in columns if c["inferred_type"] == "xsd:dateTime"}
    bool_fields = {c["column_name"]: f"ioi-ext:{_to_property_name(artifact_name, c['clean_name'])}"
                   for c in columns if c["inferred_type"] == "xsd:boolean"}
    str_fields  = {c["column_name"]: f"ioi-ext:{_to_property_name(artifact_name, c['clean_name'])}"
                   for c in columns
                   if c["inferred_type"] not in ("xsd:integer", "xsd:dateTime", "xsd:boolean")}

    script_lines = [
        '#!/usr/bin/env python3',
        f'"""',
        f'{artifact_name} Instantiator',
        f'AUTO-GENERATED by IOI MCP Server — generate_instantiator tool.',
        f'Artifact: {artifact_name} | Facet: ioi-ext:{facet_name}',
        f'"""',
        'import csv, json, uuid, copy',
        'from datetime import datetime, timezone',
        'from pathlib import Path',
        '',
        f'ARTIFACT_NAME = "{artifact_name}"',
        f'FACET_TYPE    = "ioi-ext:{facet_name}"',
        f'TEMPLATE_DIR  = Path(__file__).parent / "templates" / "{art_lower}"',
        '',
        f'INTEGER_FIELDS  = {fmt_dict(int_fields)}',
        f'DATETIME_FIELDS = {fmt_dict(dt_fields)}',
        f'BOOLEAN_FIELDS  = {fmt_dict(bool_fields)}',
        f'STRING_FIELDS   = {fmt_dict(str_fields)}',
        '',
        'DEFAULT_TIMESTAMP = "1970-01-01T00:00:00Z"',
        '',
        'def sanitize_int(v, default="0"):',
        '    try: return str(int(float(str(v).strip())))',
        '    except: return default',
        '',
        'def sanitize_timestamp(v, default=DEFAULT_TIMESTAMP):',
        '    if not v or not str(v).strip(): return default',
        '    s = str(v).strip()',
        '    try:',
        '        dt = datetime.fromisoformat(s.replace("Z", "+00:00"))',
        '        return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")',
        '    except:',
        '        return s',
        '',
        'def load_templates():',
        f'    with open(TEMPLATE_DIR / "{art_lower}_template_base.json") as f: base = json.load(f)',
        f'    with open(TEMPLATE_DIR / "{art_lower}_template-source_file.json") as f: src = json.load(f)',
        f'    with open(TEMPLATE_DIR / "{art_lower}_template-entry_clean.json") as f: entry = json.load(f)',
        f'    with open(TEMPLATE_DIR / "{art_lower}_template-action.json") as f: action = json.load(f)',
        '    return base, src, entry, action',
        '',
        'def fill_template_from_csv(csv_path, output_path):',
        '    base, src_tmpl, entry_tmpl, action_tmpl = load_templates()',
        '    with open(csv_path, encoding="utf-8-sig") as f:',
        '        rows = list(csv.DictReader(f))',
        '',
        '    src_uuid = str(uuid.uuid4())',
        '    source   = copy.deepcopy(src_tmpl[0])',
        '    raw      = json.dumps(source)',
        '    raw      = raw.replace("{SOURCE_UUID}", src_uuid)',
        '    raw      = raw.replace("{SOURCE_FILENAME}", Path(csv_path).name)',
        '    raw      = raw.replace("{SOURCE_FILEPATH}", str(csv_path))',
        '    raw      = raw.replace("{SOURCE_SIZE}", str(len(rows) * 200))',
        '    source   = json.loads(raw)',
        '',
        '    entries, actions = [], []',
        '    for row in rows:',
        '        eu = str(uuid.uuid4())',
        '        au = str(uuid.uuid4())',
        '        e  = json.loads(json.dumps(copy.deepcopy(entry_tmpl[0]))',
        '                        .replace("{ENTRY_UUID}", eu))',
        '        a  = json.loads(json.dumps(copy.deepcopy(action_tmpl[0]))',
        '                        .replace("{ENTRY_UUID}", eu)',
        '                        .replace("{ACTION_UUID}", au)',
        '                        .replace("{SOURCE_UUID}", src_uuid))',
        '',
        '        for facet in e.get("core:hasFacet", []):',
        '            if FACET_TYPE in str(facet.get("@type", "")):',
        '                for col, prop in INTEGER_FIELDS.items():',
        '                    if col in row: facet[prop] = {"@type":"xsd:integer","@value":sanitize_int(row[col])}',
        '                for col, prop in DATETIME_FIELDS.items():',
        '                    if col in row: facet[prop] = {"@type":"xsd:dateTime","@value":sanitize_timestamp(row[col])}',
        '                for col, prop in BOOLEAN_FIELDS.items():',
        '                    if col in row: facet[prop] = {"@type":"xsd:boolean","@value":"true" if str(row[col]).lower() in ("true","1","yes") else "false"}',
        '                for col, prop in STRING_FIELDS.items():',
        '                    if col in row: facet[prop] = row[col] or ""',
        '',
        '        entries.append(e)',
        '        actions.append(a)',
        '',
        '    final = copy.deepcopy(base)',
        '    final["@graph"] = [source] + entries + actions',
        '    with open(output_path, "w") as f:',
        '        json.dump(final, f, indent=2, ensure_ascii=False)',
        f'    print(f"Generated: {{output_path}} ({{len(entries)}} entries)")',
        '',
        'def main():',
        '    import argparse',
        f'    p = argparse.ArgumentParser(description=f"{artifact_name} Instantiator")',
        '    p.add_argument("input",  help="Input CSV")',
        '    p.add_argument("output", help="Output JSON-LD")',
        '    args = p.parse_args()',
        '    fill_template_from_csv(args.input, args.output)',
        '',
        'if __name__ == "__main__":',
        '    main()',
    ]
    return "\n".join(script_lines) + "\n"


# ── Turtle patch ──────────────────────────────────────────────────────────────

def _make_turtle_patch(artifact_name: str, facet_name: str, columns: list) -> str:
    lines = [
        f"# {artifact_name} — auto-generated by ioi-mcp generate_instantiator",
        "",
        f"ioi-ext:{facet_name} a owl:Class ;",
        f'    rdfs:subClassOf uco-core:Facet ;',
        f'    rdfs:label "{facet_name}"@en ;',
        f'    rdfs:comment "Properties extracted from {artifact_name} forensic artifact."@en .',
        "",
    ]
    for col in columns:
        prop = _to_property_name(artifact_name, col["clean_name"])
        xsd  = col["inferred_type"]
        lines += [
            f"ioi-ext:{prop} a owl:DatatypeProperty ;",
            f"    rdfs:domain ioi-ext:{facet_name} ;",
            f"    rdfs:range {xsd} ;",
            f'    rdfs:label "{col["column_name"]}"@en ;',
            f'    rdfs:comment "Property from {artifact_name}: {col["column_name"]}"@en .',
            "",
        ]
    return "\n".join(lines)


# ── Registry entry builder ────────────────────────────────────────────────────

def _make_registry_entry(artifact_name: str, facet_name: str,
                          columns: list, artifact_id: str) -> dict:
    art_lower = artifact_name.lower()
    return {
        "artifact_id":        artifact_id,
        "full_name":          artifact_name,
        "parser_tool":        "(set parser tool)",
        "input_format":       "CSV",
        "facet":              f"ioi-ext:{facet_name}",
        "instantiator":       f"instantiators/{art_lower}_instantiator.py",
        "template_dir":       f"instantiators/templates/{art_lower}/",
        "status":             "Community",
        "cases":              [],
        "rules":              [],
        "file_facet_columns": [],
        "field_types": {
            "integer":  [c["column_name"] for c in columns if c["inferred_type"] == "xsd:integer"],
            "datetime": [c["column_name"] for c in columns if c["inferred_type"] == "xsd:dateTime"],
            "boolean":  [c["column_name"] for c in columns if c["inferred_type"] == "xsd:boolean"],
            "string":   [c["column_name"] for c in columns
                         if c["inferred_type"] not in ("xsd:integer","xsd:dateTime","xsd:boolean")],
        },
    }


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_instantiator(
    artifact_name: str,
    csv_path: str,
    output_base_dir: Optional[str] = None,
    column_mapping: Optional[dict] = None,
) -> dict:
    """
    Generate everything needed to register a new artifact in the IoI Framework.

    Args:
        artifact_name:    e.g. "Prefetch", "SRUM", "Amcache"
        csv_path:         path to a sample CSV from the artifact parser
        output_base_dir:  where to write files (defaults to IOI_FRAMEWORK_PATH
                          env if set, else /tmp/ioi_generated/{artifact_lower}/)
        column_mapping:   optional explicit column → property overrides

    Returns dict with paths to all generated files + registry entry + flow_state.
    """
    import os

    art_lower  = artifact_name.lower().replace(" ", "_")
    facet_name = _to_facet_name(artifact_name)
    columns    = analyze_csv(csv_path)

    if output_base_dir is None:
        fw_path = os.environ.get("IOI_FRAMEWORK_PATH")
        output_base_dir = fw_path if fw_path else f"/tmp/ioi_generated/{art_lower}"

    base     = Path(output_base_dir)
    inst_dir = base / "instantiators"
    tmpl_dir = base / "instantiators" / "templates" / art_lower
    inst_dir.mkdir(parents=True, exist_ok=True)
    tmpl_dir.mkdir(parents=True, exist_ok=True)

    files_created = {}

    # Templates
    for name, content in [
        (f"{art_lower}_template_base.json",         _make_base_template(art_lower)),
        (f"{art_lower}_template-source_file.json",  _make_source_template(art_lower)),
        (f"{art_lower}_template-entry_clean.json",  _make_entry_template(art_lower, facet_name, columns)),
        (f"{art_lower}_template-action.json",       _make_action_template(art_lower)),
    ]:
        p = tmpl_dir / name
        p.write_text(json.dumps(content, indent=2))
        files_created[name] = str(p)

    # Python instantiator
    p = inst_dir / f"{art_lower}_instantiator.py"
    p.write_text(_make_instantiator_script(artifact_name, facet_name, columns))
    files_created["instantiator_script"] = str(p)

    # Turtle patch (returned as string, not written to file — user appends to ioi-ext.ttl)
    turtle = _make_turtle_patch(artifact_name, facet_name, columns)
    files_created["turtle_patch"] = turtle

    # Registry entry
    artifact_id = f"ART-{str(uuid.uuid4())[:8].upper()}"
    reg_entry   = _make_registry_entry(artifact_name, facet_name, columns, artifact_id)
    files_created["registry_entry"] = reg_entry

    # Append to bundled ioi_registry.json
    bundled = Path(__file__).parent / "data" / "ioi_registry.json"
    if bundled.exists():
        with open(bundled) as f:
            reg = json.load(f)
        if artifact_name not in reg.get("artifacts", {}):
            reg["artifacts"][artifact_name] = reg_entry
            with open(bundled, "w") as f:
                json.dump(reg, f, indent=2)
            files_created["registry_updated"] = str(bundled)

    return {
        "artifact_name":  artifact_name,
        "facet":          f"ioi-ext:{facet_name}",
        "columns_found":  len(columns),
        "files_created":  files_created,
        "next_steps": [
            f"resolve_artifact('{artifact_name}') now returns a registry hit",
            f"Review {files_created.get('instantiator_script')} — set file_facet_columns manually",
            "Add turtle_patch to IoI-Framework/ontologies/ioi-ext.ttl",
            "PR files to IoI-Framework: instantiators/ + registry.json + ioi-ext.ttl",
        ],
        "flow_state": {
            "step_completed": "generate_instantiator",
            "path":           "new_artifact → known_artifact",
            "next": {
                "primary": f"generate_all_rows('{artifact_name}', csv_path, column_mapping={{}}, registry_entry=registry.resolve('{artifact_name}'))",
                "note":    "Artifact is now registered — canonical path active from this session onward",
            },
        },
    }
